// Copyright 2026 Gilles Reant. SPDX-License-Identifier: Apache-2.0
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import vm from 'node:vm';
const write = process.argv.includes('--write');
const root = path.resolve('public');
const failures = [];
const digest = content => 'sha256-' + crypto.createHash('sha256').update(content).digest('base64');
function update(file, text) {
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === text) return;
  if (write) fs.writeFileSync(file, text);
  else failures.push(`${file}: generated metadata is stale; run node tools/audit.mjs --write`);
}
// Normalize first-party source line endings before computing browser SRI hashes.
for (const file of fs.readdirSync(root).filter(name => /\.(js|mjs|html)$/.test(name))) {
  const full = path.join(root, file), source = fs.readFileSync(full, 'utf8');
  if (write && source.includes('\r')) fs.writeFileSync(full, source.replace(/\r\n/g, '\n'));
  if (file.endsWith('.js')) new vm.Script(source, { filename: file });
}
const manifestPath = path.join(root, 'vendor/manifest.json');
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
for (const entry of manifest.dependencies) {
  entry.sha256 = digest(fs.readFileSync(path.join(root, 'vendor', entry.file)));
  for (const license of [entry.licenseFile, ...(entry.bundledNotices || [])]) {
    if (!fs.existsSync(path.join(root, 'vendor', license))) failures.push(`Missing license: ${license}`);
  }
}
update(manifestPath, JSON.stringify(manifest, null, 2) + '\n');
const workerPolicy = "default-src 'none'; script-src 'self' blob: 'unsafe-eval'; connect-src 'self'";
const headerHashes = new Set();
for (const file of fs.readdirSync(root).filter(name => name.endsWith('.html'))) {
  const full = path.join(root, file);
  let html = fs.readFileSync(full, 'utf8');
  const inlineHashes = [];
  for (const match of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)) {
    if (!/\bsrc=/.test(match[1]) && match[2].trim()) inlineHashes.push("'" + digest(match[2]) + "'");
  }
  inlineHashes.forEach(hash => headerHashes.add(hash));
  const policy = `default-src 'self'; script-src 'self' ${inlineHashes.join(' ')}; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; worker-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'`;
  html = html.replace(/\n    <meta http-equiv="Content-Security-Policy" content="[^"]*">/g, '');
  html = html.replace('    <meta charset="utf-8">', `    <meta charset="utf-8">\n    <meta http-equiv="Content-Security-Policy" content="${policy}">`);
  html = html.replace(/<script\b[^>]*\bsrc="([^"]+)"[^>]*>/g, (tag, src) => {
    if (/^(https?:)?\/\//.test(src)) { failures.push(`${file}: external script ${src}`); return tag; }
    const asset = path.resolve(root, src);
    if (!asset.startsWith(root + path.sep) || !fs.existsSync(asset)) { failures.push(`${file}: missing script ${src}`); return tag; }
    return tag.replace(/\s+integrity="[^"]*"/g, '').replace(/>$/, ` integrity="${digest(fs.readFileSync(asset))}">`);
  });
  for (const match of html.matchAll(/\b(?:src|href)="([^"#]+)"/g)) {
    const target = match[1].split(/[?#]/)[0];
    if (!/^(?:https?:|data:|blob:|mailto:|\/\/)/.test(target) && !fs.existsSync(path.join(root, target))) failures.push(`${file}: missing local link ${target}`);
  }
  update(full, html);
}
const policy = `default-src 'self'; script-src 'self' ${[...headerHashes].join(' ')}; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self'; worker-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'`;
update(path.join(root, '.htaccess'), `# Generated by tools/audit.mjs. Apache mod_headers and AllowOverride FileInfo required.\nOptions -Indexes\nAddType text/javascript .mjs\nAddType application/manifest+json .webmanifest\n<IfModule mod_headers.c>\n  Header always set X-Content-Type-Options "nosniff"\n  Header always set Referrer-Policy "no-referrer"\n  Header always set Permissions-Policy "camera=(self), microphone=()"\n  Header always set Content-Security-Policy "${policy}"\n  <Files "qr-worker.js">\n    Header always set Content-Security-Policy "${workerPolicy}"\n  </Files>\n  <Files "service-worker.js">\n    Header always set Cache-Control "no-cache"\n  </Files>\n</IfModule>\n`);
const sw = fs.readFileSync(path.join(root, 'service-worker.js'), 'utf8');
const assets = [...sw.match(/const ASSETS = \[([\s\S]*?)\];/)[1].matchAll(/'([^']+)'/g)].map(match => match[1]);
for (const asset of assets) if (!fs.existsSync(path.join(root, asset))) failures.push(`Missing precache asset ${asset}`);
for (const file of fs.readdirSync(root).filter(name => /\.(html|js|mjs|css)$/.test(name) && !['service-worker.js', 'cbor-base64url.js'].includes(name))) if (!assets.includes('./' + file)) failures.push(`Missing from precache: ${file}`);
const cvHash = manifest.dependencies.find(entry => entry.name === 'OpenCV.js').sha256;
if (!fs.readFileSync(path.join(root, 'opencv-loader.js'), 'utf8').includes(cvHash)) failures.push('OpenCV loader integrity does not match the vendored artifact.');
const version = fs.readFileSync('NOTICE', 'utf8').match(/^Version (\d+\.\d+\.\d+)$/m)?.[1];
if (!version || !sw.includes(version) || !fs.readFileSync('README.md', 'utf8').includes(`Current application version: **${version}**`) || !fs.readFileSync(path.join(root, 'about.html'), 'utf8').includes(`<dd>${version}</dd>`)) failures.push('Release version differs between NOTICE, README, About and service worker.');
if (failures.length) { console.error(failures.join('\n')); process.exitCode = 1; }
else console.log(`Audit passed: ${manifest.dependencies.length} pinned dependencies, ${assets.length} precache paths, all page script hashes, CSP and local links.`);
