# Copyright 2026 Gilles Reant. SPDX-License-Identifier: Apache-2.0
# Development-only: downloads pinned public datasets and regenerates static lookups.
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$sources = @(
  @{ Repo='greggles/mcc-codes'; Revision='df792275c567946119a8903d36dbd33e44a248bf'; Path='mcc_codes.json'; File='mcc-codes.js'; Global='mccCodes'; Kind='mcc' },
  @{ Repo='datasets/currency-codes'; Revision='7cdc784a3090d253721a1f00cfd5843b46a4dc64'; Path='data/codes-all.csv'; File='iso4217-codes.js'; Global='iso4217Codes'; Kind='currency' },
  @{ Repo='datasets/country-codes'; Revision='6a595f1a6f10b3d00175fe67375da88f64f7f76b'; Path='data/country-codes.csv'; File='iso3166-alpha2-codes.js'; Global='iso3166Alpha2Codes'; Kind='country' },
  @{ Repo='datasets/language-codes'; Revision='2787e945225a6daaa75d9f3812a977c9f89c61bc'; Path='data/language-codes.csv'; File='iso639-language-codes.js'; Global='iso639LanguageCodes'; Kind='language' }
)
foreach ($source in $sources) {
  $url = "https://raw.githubusercontent.com/$($source.Repo)/$($source.Revision)/$($source.Path)"
  $content = (Invoke-WebRequest -Uri $url).Content
  $lookup = [System.Collections.Generic.SortedDictionary[string,object]]::new([System.StringComparer]::Ordinal)
  if ($source.Kind -eq 'mcc') {
    foreach ($row in ($content | ConvertFrom-Json)) { $lookup[$row.mcc] = $row.combined_description }
  } else {
    foreach ($row in ($content | ConvertFrom-Csv)) {
      switch ($source.Kind) {
        'currency' { if ($row.NumericCode -match '^\d{3}$' -and !$row.WithdrawalDate) { $lookup[$row.NumericCode] = [ordered]@{alpha=$row.AlphabeticCode; name=$row.Currency; minorUnit=$row.MinorUnit} } }
        'country' { if ($row.'ISO3166-1-Alpha-2' -match '^[A-Z]{2}$') { $lookup[$row.'ISO3166-1-Alpha-2'] = $row.'CLDR display name' } }
        'language' { if ($row.alpha2 -match '^[a-z]{2}$') { $lookup[$row.alpha2] = $row.English } }
      }
    }
  }
  $json = ($lookup | ConvertTo-Json -Depth 6).Replace("`r`n", "`n")
  $output = "// Generated by tools/generate-lookups.ps1. Source: $url`n// Dataset license: $($source.File.Replace('.js','.LICENSE.txt'))`n(function (global) {`n  global.$($source.Global) = $json;`n}(globalThis));`n"
  [System.IO.File]::WriteAllText((Join-Path $root "public/vendor/$($source.File)"), $output, [System.Text.UTF8Encoding]::new($false))
  Write-Output "Generated $($source.File): $($lookup.Count) entries"
}
